server:
  port: 8080

lzp:
  baseUrl: https://m.weibo.cn/
  urlFirst: api/container/getIndex?uid=6027016891&t=0&luicode=10000011&lfid=100103type=1&q=李壮平&type=uid&value=6027016891&containerid=1076036027016891
  header: "{cookie: '设置你自己的cookie'}"

spring:
#  数据源
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useSSL=false
    username: root
    password: 1111
#表不存在就创建
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#远程调试
wbrepl:
  host: 127.0.0.1
  port: 55555
  enabled: true